import { useState } from 'react';
import { createId, Shell, Stat, useLocal } from './shared';
import { moveTask } from './domain';
type Task = {
    id: string;
    title: string;
    priority: string;
    status: number;
};
const columns = ['A fazer', 'Em andamento', 'Concluído'];
export default function App() { const [tasks, setTasks, error] = useLocal<Task[]>('flowboard-v1', [{ id: '1', title: 'Definir tokens de design', priority: 'Alta', status: 0 }, { id: '2', title: 'Construir navegação acessível', priority: 'Alta', status: 1 }, { id: '3', title: 'Documentar arquitetura', priority: 'Média', status: 2 }]); const [search, setSearch] = useState(''); function add(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const title = String(f.get('title')).trim(); if (!title)
    return; setTasks([...tasks, { id: createId(), title, priority: String(f.get('priority')), status: 0 }]); e.currentTarget.reset(); } return <Shell name="Flowboard" title="Do plano à entrega." description="Um espaço para manter o foco: organize o trabalho, defina prioridades e acompanhe cada entrega." accent="#b3a1ff">{error && <p role="alert">Não foi possível persistir tarefas.</p>}<div className="grid"><Stat label="Total de tarefas" value={tasks.length}/><Stat label="Em andamento" value={tasks.filter(x => x.status === 1).length}/><Stat label="Concluídas" value={tasks.filter(x => x.status === 2).length}/></div><section className="panel" style={{ marginTop: 24 }}><form className="form" onSubmit={add}><label>Nova tarefa<input name="title" maxLength={120} required/></label><label>Prioridade<select name="priority"><option>Alta</option><option>Média</option><option>Baixa</option></select></label><button className="primary">Criar tarefa</button></form><label style={{ marginTop: 20 }}>Buscar tarefas<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Digite uma palavra…"/></label></section><div className="grid">{columns.map((col, index) => <section className="panel" key={col}><div className="row spread"><h2>{col}</h2><span className="tag">{tasks.filter(t => t.status === index).length}</span></div>{tasks.filter(t => t.status === index && t.title.toLowerCase().includes(search.toLowerCase())).map(t => <article className="card" key={t.id}><span className="eyebrow">{t.priority}</span><h3 style={{ marginTop: 12 }}>{t.title}</h3><label>Mover para<select value={t.status} onChange={e => setTasks(moveTask(tasks, t.id, Number(e.target.value)))}>{columns.map((c, i) => <option key={c} value={i}>{c}</option>)}</select></label><button style={{ marginTop: 12 }} aria-label={'Excluir ' + t.title} onClick={() => setTasks(tasks.filter(x => x.id !== t.id))}>Excluir</button></article>)}{!tasks.some(t => t.status === index && t.title.toLowerCase().includes(search.toLowerCase())) && <p className="empty">Nenhuma tarefa por aqui.</p>}</section>)}</div></Shell>; }
